# Generated by Django 6.0.3 on 2026-03-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='price_per_post',
            field=models.IntegerField(default=0),
        ),
    ]
