# Generated by Django 6.0.2 on 2026-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_alter_influencerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_photos/'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
