# Generated by Django 6.0.2 on 2026-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencerprofile_city_influencerprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_banners/'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='influencer_profiles/'),
        ),
    ]
